### ISSUE TITLE
Types don't match docs

### ISSUE THREAD

**Issue by chmac** [ThaUnknown/uint8-util#2]
Readme says:

```js
const str = arr2text(new Uint8Array([1, 2, 3]))
```

index.d.ts says:

```ts
export function arr2text (data: ArrayBuffer | Uint8Array, enc: Encoding): string
```

I guess the type should be `enc?: Encoding` so it's an optional second parameter.

**Comment by ThaUnknown** [comment]
probs, i never worked with typescript types
