### ISSUE TITLE
Doesn't actually returns binary (like nodejs does)

### ISSUE THREAD

**Issue by VandeurenGlenn** [ThaUnknown/uint8-util#3]
Is it me or is it time to really return binary?
Or what I'm missing?

https://github.com/ThaUnknown/uint8-util/blob/149c44c010b3ad17a7904c4266545bbca1fd4403/browser.js#L36C14-L36C21

**Comment by ThaUnknown** [comment]
this is binary encoded string, an equal for node buffer's Buffer.toString('binary') except it takes a hex string as an input not a buffer, as from experience the only places you'd need this kind of binary encoded string is when working with hex

**Comment by ThaUnknown** [comment]
if you want uint8 array data use hex2arr which converts a hex string to uint8, X2arr converts X to uint8 and arr2X converts uint8 or an array of int to X

**Comment by VandeurenGlenn** [comment]
@ThaUnknown Uhu, I understand, but the main question is why isn't it really binary and instead just gives utf8 string back?

<img width="279" alt="image" src="https://github.com/ThaUnknown/uint8-util/assets/8685280/62bdfd98-ed82-4b91-b1c6-9937b394c01d">

I know it's following the node way, but since that doesn't really return binary my question was isn't it time to break that?
A binary string is a sequence of 0's and 1's and doesn't contain characters.

**Comment by ThaUnknown** [comment]
no, this package is meant as a bridge for other apps and packages to deprecate buffer, in place without actually changing any functionality, so if they used Buffer.toString('binary') they'd need this function, this is binary encded, not binary

**Comment by ThaUnknown** [comment]
as per this package's description `This libraries brings features from Node's Buffer to JS's Uint8Arrays and in some cases other Typed Arrays, in the fastest ways possible, often faster than Node's own Buffer's methods.`

it doesnt create new methods, just bridges established ones to a faster more modern method
